name: Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: fetch shallow git history
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: install dependencies
        run: yarn install
      - name: build packages
        run: yarn build
      - name: test packages
        env:
          CI: true
        run: yarn test
